### ISSUE TITLE
Arrangement for action buttons

### ISSUE THREAD

**Issue by pararang** [pararang/visitor-app#2]
Arrangement for action buttons.

![Screenshot from 2019-10-19 22-04-43](https://user-images.githubusercontent.com/8720184/67147191-d2727280-f2bc-11e9-8df2-33a969684cba.png)

**Comment by Bhavesh27** [comment]
![Screenshot 2019-10-19 at 9 15 15 PM](https://user-images.githubusercontent.com/20737807/67147791-d18a1280-f2b5-11e9-90d0-206565ec49de.png)
is this good enough or need more improvement

**Comment by pararang** [comment]
yes, it's good. @Bhavesh27

**Comment by Bhavesh27** [comment]
created a pull request

**Comment by pararang** [comment]
thanks @Bhavesh27
