### ISSUE TITLE
Fix styling for buttons wrapper on action column

### ISSUE THREAD

**Issue by pararang** [pararang/visitor-app#6]
![Screenshot from 2019-10-20 00-04-14](https://user-images.githubusercontent.com/8720184/67148810-f25e6200-f2cd-11e9-840d-4321fde16569.png)

**Comment by deividynegri** [comment]
I can work on this... could you give me more details about what you want?

**Comment by pararang** [comment]
Halo @deividynegri , yes you can. as you can see on the screenshot, the line of the action button column not inline with the others column

![Screenshot from 2019-10-20 00-18-25](https://user-images.githubusercontent.com/8720184/67148924-40c03080-f2cf-11e9-88ab-07b6504b26d6.png)

**Comment by deividynegri** [comment]
Ok, working on it

**Comment by deividynegri** [comment]
Does it work for you?
I also had to change the name of the class 'container' because it's a class used by your css framework (:

![image](https://user-images.githubusercontent.com/7256145/67149639-fbc2dc80-f283-11e9-8521-0dc20f3c4a73.png)
